name: PHP_CodeSniffer

on:
  workflow_call:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: bcmath, intl, mbstring, mysql
          ini-values: memory_limit=2048M
          tools: composer, cs2pr
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs -q --report=checkstyle | cs2pr
