name: PHP_CodeSniffer

on:
  workflow_call:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP_CodeSniffer
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: vendor/bin/phpcs
