name: PHPStan

on:
  workflow_call:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install PHPStan
      run: composer bin phpstan install

    - name: Run PHPStan
      run: composer run-script phpstan
