name: Psalm

on:
  workflow_call:

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Psalm
        run: composer bin psalm install

      - name: Run Psalm
        run: composer run-script psalm
